// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220523134905_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication1.Models.People.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Gothenburg",
                            Name = "Benjamin Nordin",
                            PhoneNumber = 555123
                        },
                        new
                        {
                            Id = 2,
                            City = "Bones Burrow",
                            Name = "Eda Clawthorn",
                            PhoneNumber = 6694875
                        },
                        new
                        {
                            Id = 3,
                            City = "Bones Burrow",
                            Name = "King Clawthorn",
                            PhoneNumber = 555213345
                        },
                        new
                        {
                            Id = 4,
                            City = "Newtopia",
                            Name = "Marcy Wou",
                            PhoneNumber = 777485632
                        },
                        new
                        {
                            Id = 5,
                            City = "Gothenburg",
                            Name = "Jonas Edenstav",
                            PhoneNumber = 31222666
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
